### ISSUE TITLE
Tasks : Incorrect color code (red) is displayed for future dated tasks 

### ISSUE THREAD

**Issue by MustafaASK** [ShaikASK/Testing#514]
Steps to Replicate : 

1. Launch the URL
2. Sign in as HR admin user
3. Create some Tasks say 
- Task 1 (July/11/2018) with open status 
- Task 2 (July/12/2018) with open status 
- Task 3 (August/2/2018)  with open status 
- Task 4 (August/28/2018)  with In progress status 

4.Save it 
5.Check the Calendar 

Experienced Behavior : Observed that Incorrect color code (red) is displayed for future dated tasks (Refer Screen shot)
Expected Behavior : Ensure that application should display proper color code for future dates 

![task](https://user-images.githubusercontent.com/31955617/42553001-6ed5d7ec-84ce-11e8-93f0-8fb1f77e150e.jpg)

**Comment by ShaikASK** [comment]
Vinay: Fixed in Dev Environment, Will be released to QA in next build (30-7-2018 6:41 PM)

**Comment by MustafaASK** [comment]
01/08/2018 - Natasha Chouhan - We have retested this on the latest Release#3 Build 17 and observed that this is working as expected , Hence marking this to close

**Comment by MustafaASK** [comment]
13/09/2018- Natasha Chouhan - We have retested this on the latest  Release#3 Build 30 and observed that this issue is still replicating, Hence marking this to reopen

**Comment by MustafaASK** [comment]
14/09/2018 - Natasha Chouhan - We have retested this on the latest Release#3 Build 31 and observed that this is working as expected , Hence marking this to close
