### ISSUE TITLE
1024 x 768 resolution : FF / Chrome : Dashboard : Fifth New Hire present on dashboard screen is not visible properly 

### ISSUE THREAD

**Issue by MustafaASK** [ShaikASK/Testing#519]
Steps  to Replicate : 

1.Switch the screen into 1024 x 768 resolution 
2.Launch the URL
3.Sign in as Hr admin user 
4.Navigate to "Dashboard" screen 
6.Check "NEW HIRES" section of "Dashboard" screen 

Experienced Behavior : Observed that  Fifth New Hire present on dashboard screen is not visible properly (Refer Screenshot)
Expected Behavior : Ensure that application should display new hires properly on the dashboard screen 

FF (61) 
![ffdashbard](https://user-images.githubusercontent.com/31955617/46596742-2fa8e500-cafb-11e8-9897-350b590174ee.jpg)

Chrome (69)
![chromedashboard](https://user-images.githubusercontent.com/31955617/46596760-3afc1080-cafb-11e8-8541-e234df60f6bf.jpg)

![ji](https://user-images.githubusercontent.com/31955617/42567310-fc389874-8526-11e8-9ca2-6c33e0ce7be9.jpg)

**Comment by ShaikASK** [comment]
Vinay : Fixed in Dev Environment, Will be released to QA in next build (30-7-2018 7:30 PM)

**Comment by MustafaASK** [comment]
01/08/2018 - Natasha Chouhan - We have retested this on the latest Release#3 Build 17 and observed that this is working as expected , Hence marking this to close

**Comment by MustafaASK** [comment]
08/10/2018 - Natasha Chouhan - We have retested this on the latest  Release#3 Build 34 and observed that this issue is still replicating, Hence marking this to reopen

**Comment by MustafaASK** [comment]
06/11/2018 - Natasha Chouhan - We have retested this on the latest Release#3 Build 38 and observed that this is working as expected , Hence marking this to close
