### ISSUE TITLE
IE (11) /FF (61) : 1024 x768 Resolution : Workflows : Alignment of uploaded document &  Documents editable while Initiate Onboarding radio option is missing 

### ISSUE THREAD

**Issue by MustafaASK** [ShaikASK/Testing#549]
Steps To Replicate : 

1. Switch to 1024 x 768 resolution 
2. Launch the URL
3. Sign in as HR admin user
4. Create a workflow with  2 steps and save it 

Experienced Behavior : Observed that uploaded document is is being displayed in workflows when check with FF(61) browser in 1024 x 768 resolution & "Documents editable while Initiate Onboarding" radio option alignment is missing when check with IE (110 in 124 x 768 resolution (Refer Screen shot)
Expected Behavior : Ensure that application should display alignment of workflows screen properly in 1024 x 768 resolution as like normal resolution 

FF(61) 
![workflow](https://user-images.githubusercontent.com/31955617/43186522-789b6a14-900c-11e8-9b69-a1433f70ecf1.jpg)

FF(11)
![alig](https://user-images.githubusercontent.com/31955617/43250023-f500a1dc-90d9-11e8-8f6d-5d70c1b75f76.jpg)

IE(11) 
![ie](https://user-images.githubusercontent.com/31955617/43186530-83130826-900c-11e8-8068-1708bafd7649.jpg)

**Comment by ShaikASK** [comment]
Anil : Fixed in Dev Environment,Will be released in next Build QA

**Comment by MustafaASK** [comment]
01/08/2018- Natasha Chouhan - We have retested this on the latest  Release#3 Build 17 and observed that this issue is partially fixed it is working fine with IE browser but in FF browser alignment of check boxes is missing (Refer screen shot) Hence marking this to reopen

![ff](https://user-images.githubusercontent.com/31955617/43502789-1ee64eda-957a-11e8-8e19-18fcd13423a4.jpg)

**Comment by MustafaASK** [comment]
09/08/2018 - Natasha Chouhan - We have retested this on the latest Release#3 Build 19 and observed that this is working as expected , Hence marking this to close
